In [14]:
import os
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [2]:
db_uri = os.getenv("FOREST_DB_URI")
db_uri

'postgresql://eem:eem26trondheim@10.13.10.67:5432/eem'

In [21]:
sql = """
SELECT
	timestamp,
	sum(co2) as co2,
	sum(mwh) as mwh
FROM grid
WHERE timestamp >= '2023-12-20 23:00'
AND timestamp <= '2024-12-31 23:00'
GROUP BY timestamp
ORDER BY timestamp ASC
"""
grid = pd.read_sql(sql, db_uri)
grid

                timestamp           co2       mwh
0     2023-12-31 23:00:00  1.814312e+09  13094.50
1     2023-12-31 23:15:00  1.811686e+09  12846.50
2     2023-12-31 23:30:00  1.784325e+09  12793.50
3     2023-12-31 23:45:00  1.777986e+09  12788.00
4     2024-01-01 00:00:00  1.778603e+09  12813.50
...                   ...           ...       ...
35132 2024-12-31 22:00:00  2.423593e+09  13404.25
35133 2024-12-31 22:15:00  2.338507e+09  13343.50
35134 2024-12-31 22:30:00  2.344266e+09  13380.50
35135 2024-12-31 22:45:00  2.322863e+09  13418.50
35136 2024-12-31 23:00:00  2.284208e+09  13580.75

[35137 rows x 3 columns]

In [22]:
timescale_uri = os.getenv("NOWUM_TIMESCALE_URI")
sql = """
    SELECT *
    FROM smard_from_2018.prices
    WHERE timestamp >= '2023-12-20 23:00'
    AND timestamp <= '2024-12-31 23:00'
    ORDER BY timestamp ASC
"""

smard = pd.read_sql(sql, timescale_uri)
smard

                timestamp commodity_id  price
0     2023-12-20 23:00:00         4169  30.16
1     2023-12-20 23:15:00         4169  30.16
2     2023-12-20 23:30:00         4169  30.16
3     2023-12-20 23:45:00         4169  30.16
4     2023-12-21 00:00:00         4169  25.08
...                   ...          ...    ...
36188 2024-12-31 22:00:00         4169   0.52
36189 2024-12-31 22:15:00         4169   0.52
36190 2024-12-31 22:30:00         4169   0.52
36191 2024-12-31 22:45:00         4169   0.52
36192 2024-12-31 23:00:00         4169   2.16

[36193 rows x 3 columns]

In [27]:
optimizations = pd.read_sql("select distinct(optimization_case_name) as optis from flexible_power", db_uri)["optis"].tolist()
power_timeseries = {}
for opti in optimizations:
    if opti not in power_timeseries.keys():
        sql = f"select * from flexible_power where optimization_case_name = '{opti}' order by timestamp asc"
        power_timeseries[opti] = pd.read_sql(sql, db_uri)

In [30]:
power_timeseries["dynamic_w4"]

,timestamp,optimization_case_name,electricity_used,low_price_window
0,2024-01-01 00:00:00,dynamic_w4,2416.49,0
1,2024-01-01 00:15:00,dynamic_w4,2470.49,0
2,2024-01-01 00:30:00,dynamic_w4,2488.49,0
3,2024-01-01 00:45:00,dynamic_w4,2263.49,0
4,2024-01-01 01:00:00,dynamic_w4,2029.49,0
...,...,...,...,...
35036,2024-12-30 23:00:00,dynamic_w4,1600.00,1
35037,2024-12-30 23:15:00,dynamic_w4,100.00,1
35038,2024-12-30 23:30:00,dynamic_w4,0.00,1
35039,2024-12-30 23:45:00,dynamic_w4,0.00,1
35040,2024-12-31 00:00:00,dynamic_w4,0.00,0

In [35]:
big_df = grid[["timestamp", "co2"]].copy()
big_df = pd.merge(big_df, smard[["timestamp", "price"]], "left", "timestamp")
for case_name, power_df in power_timeseries.items():
    power_df = power_df.rename(columns={"electricity_used": case_name})[["timestamp", case_name]]
    big_df = pd.merge(big_df, power_df, "left", "timestamp")

big_df = big_df.dropna()
corr_df = big_df.corr()
corr_df

,timestamp,co2,price,dynamic_w4,dynamic_w4_no_flh,dynamic_w4_no_flh_wAllowed24h,dynamic_w4_wAllowed24h,dynamic_w6,dynamic_w6_no_flh,dynamic_w6_wAllowed24h,static
timestamp,1.000000,0.060758,0.248942,0.020014,0.037896,0.037250,0.025008,0.025844,0.037542,0.024536,0.024709
co2,0.060758,1.000000,0.632015,-0.411154,-0.480618,-0.481041,-0.409196,-0.433062,-0.485487,-0.429380,-0.503123
price,0.248942,0.632015,1.000000,-0.485603,-0.568186,-0.568877,-0.488398,-0.510062,-0.571329,-0.505720,-0.571963
dynamic_w4,0.020014,-0.411154,-0.485603,1.000000,0.854201,0.839144,0.916142,0.902113,0.836572,0.870559,0.727904
dynamic_w4_no_flh,0.037896,-0.480618,-0.568186,0.854201,1.000000,0.989918,0.842716,0.873765,0.987562,0.860501,0.854048
dynamic_w4_no_flh_wAllowed24h,0.037250,-0.481041,-0.568877,0.839144,0.989918,1.000000,0.856759,0.867556,0.983090,0.864657,0.855648
dynamic_w4_wAllowed24h,0.025008,-0.409196,-0.488398,0.916142,0.842716,0.856759,1.000000,0.875372,0.833735,0.880628,0.728364
dynamic_w6,0.025844,-0.433062,-0.510062,0.902113,0.873765,0.867556,0.875372,1.000000,0.891129,0.943892,0.764081
dynamic_w6_no_flh,0.037542,-0.485487,-0.571329,0.836572,0.987562,0.983090,0.833735,0.891129,1.000000,0.873467,0.864239
dynamic_w6_wAllowed24h,0.024536,-0.429380,-0.505720,0.870559,0.860501,0.864657,0.880628,0.943892,0.873467,1.000000,0.747779
static,0.024709,-0.503123,-0.571963,0.727904,0.854048,0.855648,0.728364,0.764081,0.864239,0.747779,1.000000

In [51]:
px.bar(corr_df.sort_values("co2"), x="co2", title="Correlation between electricity used and CO2-intensity in grid per scenario")

In [52]:
px.bar(corr_df.sort_values("price"), x="price", title="Correlation between electricity used and electricity price per scenario")